# Crosses 54 shield config
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_RESET=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_POSITION_TRIGGER=y

